cameras:
- host: mock-camera-1
  labels:
    building: A
    location: entrance
  name: camera-1
  path: /
  port: 8554
- host: mock-camera-2
  labels:
    building: B
    location: parking
  name: camera-2
  path: /
  port: 8554
- host: mock-camera-3
  labels:
    building: A
    location: server-room
  name: camera-3
  path: /
  port: 8554
