cameras:
- host: mock-camera-1
  labels:
    building: A
    location: entrance
  name: camera-1
  path: /
  port: 8554
  vendor: mock
- host: mock-camera-2
  labels:
    building: B
    location: parking
  name: camera-2
  path: /
  port: 8554
  vendor: mock
- host: mock-camera-3
  labels:
    building: A
    location: server-room
  name: camera-3
  path: /
  port: 8554
  vendor: mock
- channel: 101
  host: 172.18.212.18
  labels:
    building: main
    location: lab
  name: hikvision-dome
  password: ***
  path: /
  port: 554
  username: admin
  vendor: hikvision
