apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: VictoriaMetrics
    uid: prometheus
    type: prometheus
    orgId: 1
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
